### ISSUE TITLE
Error in StorjObj = LibUplinkPy()

### ISSUE THREAD

**Issue by mat-l** [utropicmedia/storj-python#4]
Dear all,
I am getting an error while executing "StorjObj = LibUplinkPy()" after installing storj with "pip install storj-python" and importing it with "from storjPython.uplinkPython import *"

Any ideas how I can solve the problem?

Best regards

```
python-BaseException
Traceback (most recent call last):
  File "/app/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/app/pycharm/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/mat/PycharmProjects/blockapp/storjconnector.py", line 216, in <module>
    StorjObj = LibUplinkPy()
  File "/home/mat/PycharmProjects/venv-blockapp/lib/python3.8/site-packages/storjPython/uplinkPython.py", line 160, in __init__
    self.m_libUplink = CDLL(so_path)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/mat/PycharmProjects/venv-blockapp/lib/python3.8/site-packages/storjPython/libuplinkc.so: cannot open shared object file: No such file or directory

```

**Comment by kmozurkewich** [comment]
@mat-l  - thanks for the note.  This project was migrated to a supported version at: https://github.com/storj-thirdparty/uplink-python

can you try:

`pip install --no-cache-dir uplink-python`

**Comment by mat-l** [comment]
Perfect that worked for me after some further challenges. Now I just need to find the correct api key. 🙈

**Comment by kmozurkewich** [comment]
@mat-l - great to hear!  Feel free to drop feedback at forum.storj.io or in the current project - https://github.com/storj-thirdparty/uplink-python
